# Generated by Django 6.0.3 on 2026-04-22 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Macike Enterprise', max_length=120)),
                ('currency_code', models.CharField(default='KES', max_length=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('receipt_footer', models.CharField(default='Thank you for shopping with Macike Enterprise.', max_length=255)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=10)),
                ('compact_mode', models.BooleanField(default=False)),
                ('default_payment_method', models.CharField(default='CASH', max_length=20)),
                ('require_phone_for_mpesa', models.BooleanField(default=True)),
                ('auto_open_receipt', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_visited', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-count', '-last_visited'],
                'unique_together': {('user', 'path')},
            },
        ),
    ]
