# Generated by Django 6.0.3 on 2026-04-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='business_address',
            field=models.CharField(blank=True, default='Mombasa, Kenya', max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='business_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='business_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='invoice_terms',
            field=models.CharField(default='Pay via M-Pesa. Payment due within 5 days.', max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Set a web/static path e.g. /static/img/macike-logo.png', max_length=255),
        ),
    ]
