server {
    listen 80;
    server_name macike.space www.macike.space;

    # Increase if users upload larger files.
    client_max_body_size 20M;

    # Static files collected by Django collectstatic.
    location /static/ {
        alias /var/www/sme_erp/static/;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000, immutable";
        access_log off;
    }

    # Reverse proxy to Gunicorn (UNIX socket).
    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn-sme_erp.sock;
    }
}
