# Generated by Django 6.0.3 on 2026-04-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='raw_callback',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='result_desc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
