# Generated by Django 6.0.3 on 2026-04-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_customer_salesinvoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
