# Generated by Django 6.0.3 on 2026-04-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_mpesa_phone_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Absolute discount applied before VAT (from line subtotal).', max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percent snapshot at checkout (for display/audit).', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
